In [1]:
import numpy as np

In [9]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [13]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
np.full((5,6), 9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.arange(1, 101, 6) # range

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55, 61, 67, 73, 79, 85, 91, 97])

In [23]:
np.linspace(1, 10, 4) 
# creates an array with first element 1, last element 10, total 4 elements and evenly spaced.

array([ 1.,  4.,  7., 10.])

In [31]:
np.linspace(0.5,5,10)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [35]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
arr.size

12

In [39]:
arr.shape

(4, 3)

In [41]:
arr.ndim

2

In [45]:
arr.dtype

dtype('int64')

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [49]:
arr.shape

(2, 3)

In [51]:
arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
a = arr.flatten()
a

array([1, 2, 3, 4, 5, 6])

In [63]:
a.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])