In [7]:
import numpy as np

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [11]:
flat = arr.flatten()

In [13]:
flat[0]

np.int64(1)

In [15]:
flat[5]

np.int64(6)

In [17]:
flat[0:5]

array([1, 2, 3, 4, 5])

In [19]:
flat[0:8:3]

array([1, 4, 7])

In [23]:
array = flat.copy()

In [25]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
array[[1,5,9]]

array([ 2,  6, 10])

In [37]:
array[array>6]

array([ 7,  8,  9, 10, 11, 12])

In [39]:
mask = array >= 5

In [41]:
array[mask]

array([ 5,  6,  7,  8,  9, 10, 11, 12])