In [7]:
import numpy as np
import random

In [36]:
# a)
array = np.random.randint(1,101, size = (3,3))
print(array,'\n\n',array.shape)

[[96 84 50]
 [97 62 82]
 [55 19 18]] 

 (3, 3)


In [48]:
# b)
flt = np.array([1.1, 2.2, 3.3])
intt = flt.astype(int)
intt

array([1, 2, 3])

In [62]:
# c)
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[[1,3,5]])
print(arr[1::2])

[2 4 6]
[2 4 6]


In [52]:
# d)
arr1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1d.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
# e)
arrmask = np.array([0, 20, 30, 40, 50, 60, 70, 80, 90, 100])
mask = arrmask > 50
arrmask[mask]

array([ 60,  70,  80,  90, 100])